### ISSUE TITLE
Unable to stream pluto channels

### ISSUE THREAD

**Issue by badtou** [fHDHR/fHDHR_plugin_origin_plutotv#14]
The following error occurs while using the latest build when attempting to stream pluto channels. and it appears to be associated only with the pluto plugin as I do not get this error when streaming channels using the stirr plugin. 

[2021-03-29 09:06:24,128] INFO - Found no NEW channels for plutotv.
[2021-03-29 09:06:24,129] INFO - Total plutotv Channel Count: 296
[2021-03-29 09:06:24,292] NOOB - Updating stirr EPG cache.
[2021-03-29 09:06:34,951] NOOB - Wrote stirr EPG cache. 23712 Programs for 208 Channels
[2021-03-29 09:06:34,964] NOOB - Updating plutotv EPG cache.
[2021-03-29 09:06:40,005] NOOB - Wrote plutotv EPG cache. 38488 Programs for 283 Channels
[2021-03-29 09:06:40,012] NOOB - Startup Tasks Complete.
[2021-03-29 09:06:40,017] INFO - SSDP Server Starting
[2021-03-29 09:06:40,019] INFO - Sending Alive message to network.
[2021-03-29 09:07:05,968] INFO - 127.0.0.1 - - [2021-03-29 09:07:05] "GET /discover.json HTTP/1.0" 200 2654 0.007588
[2021-03-29 09:07:05,979] INFO - 127.0.0.1 - - [2021-03-29 09:07:05] "GET /lineup_status.json HTTP/1.0" 200 2420 0.008361
[2021-03-29 09:07:08,947] INFO - 127.0.0.1 - - [2021-03-29 09:07:08] "GET /discover.json HTTP/1.0" 200 2654 0.007823
[2021-03-29 09:07:08,957] INFO - 127.0.0.1 - - [2021-03-29 09:07:08] "GET /lineup_status.json HTTP/1.0" 200 2420 0.007106
[2021-03-29 09:07:20,277] INFO - Tuner #0 Acquired.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/james/PlutoTV/fHDHR_web/api/tuners.py", line 20, in __call__
    return self.get(*args)
  File "/home/james/PlutoTV/fHDHR_web/api/tuners.py", line 151, in get
    stream_args = self.fhdhr.device.tuners.get_stream_info(stream_args)
  File "/home/james/PlutoTV/fHDHR/device/tuners/__init__.py", line 243, in get_stream_info
    stream_args["true_content_type"] = channel_stream_url_headers['Content-Type']
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
2021-03-29T14:07:20Z {'REMOTE_ADDR': '192.168.0.4', 'REMOTE_PORT': '55632', 'HTTP_HOST': 'ubuntumedia:5001', (hidden keys: 22)} failed with KeyError

[2021-03-29 09:07:20,764] INFO - 192.168.0.4 - - [2021-03-29 09:07:20] "GET /api/tuners?method=stream&channel=1a6861ce-86be-45a7-b2b9-df9dae375533&origin=plutotv HTTP/1.1" 500 161 0.488909
[2021-03-29 09:07:20,771] INFO - Tuner #1 Acquired.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 999, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.8/dist-packages/gevent/pywsgi.py", line 945, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/james/PlutoTV/fHDHR_web/api/tuners.py", line 20, in __call__
    return self.get(*args)
  File "/home/james/PlutoTV/fHDHR_web/api/tuners.py", line 151, in get
    stream_args = self.fhdhr.device.tuners.get_stream_info(stream_args)
  File "/home/james/PlutoTV/fHDHR/device/tuners/__init__.py", line 243, in get_stream_info
    stream_args["true_content_type"] = channel_stream_url_headers['Content-Type']
  File "/usr/lib/python3/dist-packages/requests/structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-type'
2021-03-29T14:07:21Z {'REMOTE_ADDR': '192.168.0.4', 'REMOTE_PORT': '55633', 'HTTP_HOST': 'ubuntumedia:5001', (hidden keys: 20)} failed with KeyError

[2021-03-29 09:07:21,065] INFO - 192.168.0.4 - - [2021-03-29 09:07:21] "GET /api/tuners?method=stream&channel=1a6861ce-86be-45a7-b2b9-df9dae375533&origin=plutotv HTTP/1.0" 500 161 0.297057
[2021-03-29 09:07:50,772] INFO - 127.0.0.1 - - [2021-03-29 09:07:50] "GET /discover.json HTTP/1.0" 200 2654 0.008224

**Comment by deathbybandaid** [comment]
Try with https://github.com/fHDHR/fHDHR/pull/167

**Comment by badtou** [comment]
As always, thanks for the quick fix.
